### ISSUE TITLE
Flushing cache from internal API

### ISSUE THREAD

**Issue by TimeZHero** [acato-plugins/wp-rest-cache#17]
Hello, I found the following line in the readme:

`*Please note:* the WP REST Cache plugin will try to detect relations in the cached data to automatically flush the cache when related items are edited, but this detection is not flawless so your caches might not be flushed automatically.`

However, there doesn't seem to be any related filter or action, and by looking at the code I can tell the methods are heavily relying on the `$cache_key` and are clearly not meant to be accessed from outside the plugin. 
It would be nice to have a way to manually add/remove related caches, execute actions whenever they are flushed and flush a given object from outside the plugin.

Please do let me know if there is an intended way and keep up the good work! :)

**Comment by richardkorthuis** [comment]
Hi,

I'm not sure if this is what you are looking for, but you could use the action `wp_rest_cache/process_cache_relations` to add extra relations to a cache. See: https://github.com/acato-plugins/wp-rest-cache/blob/master/includes/caching/class-caching.php#L860-L872

We do not have any action for whenever a cache is flushed. This is because of performance reasons, we almost always flush multiple caches at the same time (an item is almost always related to multiple caches). We do this with one database query (and schedule a cron for the actual cache cleanup. In order to be able to fire an action whenever a cache is flushed we would have to retrieve all caches that are about to be flushed and fire the action for each seperate cache.

You could do something like `\WP_Rest_Cache_Plugin\Includes\Caching\Caching::get_instance()->delete_related_caches( $id, $post_type );` to flush related caches from outside the plugin.

**Comment by TimeZHero** [comment]
I see, that's great!

Thank you very much for taking the time to answer my question, have a great day :)
